apiVersion: v1
kind: PersistentVolume
metadata:
  name: smtrader-local-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/<your-username>/smtrader-volumes"  # Replace accordingly
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smtrader-local-pvc
  namespace: smtrader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
